name: Build

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - master
    - develop
    - 'feature/**'
    - 'enhancement/**'
    - 'hostfix/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm i -g nyc typescript
    - run: tsc
    - run: npm run test:cov