name: Deploy

on:
  push:
    branches:
    - master


jobs:
  publish:
    name: npm-publish
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Checking for missing change logs...
      run: node common/scripts/install-run-rush.js change -v
    - name: Installing...
      run: node common/scripts/install-run-rush.js install
    - name: Building...
      run: node common/scripts/install-run-rush.js rebuild --verbose
    - name: Publishing...
      run: >-
        node common/scripts/install-run-rush.js publish
        --target-branch master
        --set-access-level public
        --tag latest
        --npm-auth-token ${{ secrets.NPM_AUTH_TOKEN }}
        --apply --publish --add-commit-details --include-all